server:
  port: 9000

spring:
  application:
    name: edge-service
  cloud:
    gateway:
      routes:
        - id: music-service
          uri: ${MUSIC_SERVICE_URL:http://localhost:8080}
          predicates:
            - Path=/music/**
          filters:
            - RewritePath=/music/(?<path>.*), /$\{path}
            - name: CircuitBreaker
              args:
                name: musicCircuitBreaker
                fallbackUri: forward:/music-fallback

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 20
        permitted-number-of-calls-in-half-open-state: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 15000
  timelimiter:
    configs:
      default:
        timeout-duration: 5s

management:
  endpoints:
    web:
      exposure:
        include: health, gateway, info, loggers, mappings
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
edge-service:
  greeting: "Hello, World! (from edge local)"
